### ISSUE TITLE
No status page after VCF submission

### ISSUE THREAD

**Issue by blthree** [Gregor-Mendel-Institute/AraGeno#17]
I was trying to test out the website yesterday, but I couldn't get any status after filling out the vcf submission form and clicking "identify". After submitting the page refreshes and the vcf/bed file upload box is cleared out, but the name and email fields are not. I'm also not getting any email that the job is in progress, so I guess I'm not getting to 

I tried with my own vcf as well as the sample vcf you provided, but the results were the same. However, the REST api worked fine for the same file. I was able to get my own local copy of the site running, and I'm getting the same behavior. Any ideas on what is causing this? 

On another note, do you have any suggestions for setting up a local copy arageno without sending jobs to an HPC? Right now I am just setting HPC and HPC_USER default values to 'none' so I can get the server to run. Ideally I'd like to send jobs to a local install of snpmatch instead.

**Comment by timeu** [comment]
Thanks for the bug report. Could you maybe also tell me which browser and OS you use ? 
I did test it using latest Chrome on Linux and it worked. Maybe there is something wrong with other browsers. I will look into it. 

Regarding the HPC: For the first version we just made it so it works with our HPC infrastructure. But ideally we would like to have something that is more configurable. One idea would be to add support for celery and make it possible to run it locally via celery workers. We will look into this.

**Comment by blthree** [comment]
OK I think I have figured out why it wasn't working for me. I have been dragging my vcf file into the upload box. If I instead click to open a file selection popup and choose my vcf that way, I can submit and it works correctly. Ironically, I noticed this because I just tried using microsoft edge browser for the first time. With edge, I cannot even get the upload box to register a file when I drag and drop a vcf file into the box. It does change colors when I hover over with a file, but no "The file X is valid" message after dropping. So for MS edge I had to click on the box to upload a file, and everything works correctly for me this way.

Previously I tried chrome and firefox on ubuntu 16.04, windows 7, and windows 10 all without success. I checked and all browsers and platforms are working for me if I click on the upload box instead of drag and dropping.

**Comment by blthree** [comment]
Also, when I click "Identify" after drag and dropping a file, it is just sending another GET request for /identify instead of a POST.

**Comment by timeu** [comment]
Thanks for the update. I will look into fixing those issues.

**Comment by timeu** [comment]
Fixed by https://github.com/Gregor-Mendel-Institute/AraGeno/pull/18
